name: Download files
# This workflow is triggered on pushes to the repository.
on: [push]
env:
  TAG: "test"

jobs:
  checkout_tag:  
    name: Checkout tag
    runs-on: ubuntu-latest
    steps:
      - run: echo $TAG
      - uses: actions/checkout@v1
      - name: Get previous tag
        id: previoustag
        if: success()
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"  
      - name: Set tag
        if: success()
        run: |
          env.TAG = "${{steps.previoustag.outputs.tag}}"
      - run: echo $TAG          